server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.220.92.71:8082/eureka
      
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
