server:
  port: 8088
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
