server:
  port: 8089
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.221.160.51:8082/eureka

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
