server:
  port: 8081

zuul:
  prefix: /api
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.220.92.71:8082/eureka
  instance:
     preferIpAddress: true

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
      preferred-networks:
        - 18.221.160.51
