server:
  port: 8081

zuul:
  prefix: /api
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.220.92.71:8082/eureka
  instance:
     preferIpAddress: true

spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
      preferred-networks:
        - (\d+)(?<!10)\.(\d+)(?<!192\.168)(?<!172\.(1[6-9]|2\d|3[0-1]))\.(\d+)\.(\d+)
